// <auto-generated />
using System;
using GroceryItemLookup.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GroceryItemLookup.Migrations
{
    [DbContext(typeof(GroceryItemLookupContext))]
    partial class GroceryItemLookupContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GroceryItemLookup.Models.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SupervisorID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SupervisorID");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("GroceryItemLookup.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Employee");

                    b.HasDiscriminator().HasValue("Employee");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GroceryItemLookup.Models.Product", b =>
                {
                    b.Property<int>("SKU")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SKU"));

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SKU");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("GroceryItemLookup.Models.Supervisor", b =>
                {
                    b.HasBaseType("GroceryItemLookup.Models.Employee");

                    b.HasDiscriminator().HasValue("Supervisor");
                });

            modelBuilder.Entity("GroceryItemLookup.Models.Department", b =>
                {
                    b.HasOne("GroceryItemLookup.Models.Supervisor", null)
                        .WithMany("Departments")
                        .HasForeignKey("SupervisorID");
                });

            modelBuilder.Entity("GroceryItemLookup.Models.Employee", b =>
                {
                    b.HasOne("GroceryItemLookup.Models.Department", null)
                        .WithMany("Supervisors")
                        .HasForeignKey("DepartmentID");
                });

            modelBuilder.Entity("GroceryItemLookup.Models.Product", b =>
                {
                    b.HasOne("GroceryItemLookup.Models.Department", null)
                        .WithMany("Products")
                        .HasForeignKey("DepartmentID");
                });

            modelBuilder.Entity("GroceryItemLookup.Models.Department", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Supervisors");
                });

            modelBuilder.Entity("GroceryItemLookup.Models.Supervisor", b =>
                {
                    b.Navigation("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
